apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: volumes-web-app
        env:
        - name: USERID_HEADER
          value: null
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-header
        - name: USERID_PREFIX
          value: null
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-prefix
