apiVersion: v1
data:
  ingressName: envoy-ingress
  istioNamespace: istio-system
  oauthSecretName: kubeflow-oauth
  appName: KUBEFLOW-NAME # {"$kpt-set":"name-label"}
  hostname: KUBEFLOW-NAME.endpoints.PROJECT.cloud.goog # {"$kpt-set":"hostname"}
  ipName: KUBEFLOW-NAME-ip # {"$kpt-set":"ip-name"}
  project: "PROJECT" # {"$kpt-set":"project"}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: iap-ingress-config
