# This package defines the overlays of all GCP infra
# config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace should match the project.
# This assumes we are running a config connector in namespace mode and
# namespaces match project names.
namespace: PROJECT # kpt-set: ${gcloud.core.project}
commonLabels:
  kf-name: KUBEFLOW-NAME # kpt-set: ${name}
resources:
# The default Google Cloud resources.
- ../cluster/upstream
- ../ingress/upstream
- ../iam/upstream
- gcp-services.yaml
# Add additional Google Cloud resources by including resources here.
# For example, uncomment the following line to include an additional example
# nodepool described in a local file ./nodepool-example.yaml.
# - nodepool-example.yaml

# You can find documentation about strategic-merge-patch in
# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md
patchesStrategicMerge:
- cluster-patch.yaml
