# This package defines the overlays of all GCP infra
# config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace should match the project.
# This assumes we are running CNRM in namespace mode and namespaces match project names.
namespace: PROJECT # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
# TODO(jlewi): do not commit the labels auto-deploy and purpose; they were added
# as part of autodeployment testing.
commonLabels:  
  kf-name: KUBEFLOW-NAME # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"KUBEFLOW-NAME"}}}
resources:
- ../../upstream/manifests/gcp/v2/cnrm
- iam_policy.yaml
patchesStrategicMerge:
- cluster_patch.yaml
